In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [6]:
np.empty((4,4))

array([[6.23042070e-307, 7.56587584e-307, 1.37961302e-306,
        1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 1.24611674e-306,
        1.29061821e-306],
       [6.23057349e-307, 1.86920193e-306, 9.34608432e-307,
        2.56765117e-312]])

In [12]:
np.arange(10,31)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [17]:
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(arr)
arr.shape

[[1 2 3]
 [2 3 4]
 [3 4 5]]


(3, 3)

In [16]:
arr.ndim

2

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr_float=arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [21]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

arr1+arr2

array([[ 6,  8],
       [10, 12]])

In [22]:
np.add(arr1,arr2)

array([[ 6,  8],
       [10, 12]])

In [23]:
arr1*arr2
np.multiply(arr1,arr2)

array([[ 5, 12],
       [21, 32]])

In [28]:
arr1.dot(arr2)
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [29]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_1=arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [31]:
arr[0,2]

3

In [32]:
arr[[0,1,2],[2,0,1]]

array([3, 4, 8])

In [33]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr=np.array([[1,2,3],[4,5,6]])
idx=arr>3
print(idx)
print(arr[idx])

[[False False False]
 [ True  True  True]]
[4 5 6]


In [41]:
whitewine=np.loadtxt(fname='C:/Users/ASIA_08/winequality-white.csv',delimiter=';',skiprows=1)
print(whitewine)

[[ 7.    0.27  0.36 ...  0.45  8.8   6.  ]
 [ 6.3   0.3   0.34 ...  0.49  9.5   6.  ]
 [ 8.1   0.28  0.4  ...  0.44 10.1   6.  ]
 ...
 [ 6.5   0.24  0.19 ...  0.46  9.4   6.  ]
 [ 5.5   0.29  0.3  ...  0.38 12.8   7.  ]
 [ 6.    0.21  0.38 ...  0.32 11.8   6.  ]]


In [42]:
whitewine.shape

(4898, 12)

In [43]:
whitewine.ndim

2

In [45]:
whitewine.dtype

dtype('float64')

In [46]:
print(whitewine.sum())

1021906.31409


In [47]:
print(whitewine.mean(axis=0)) #열 데이터 계산

[6.85478767e+00 2.78241119e-01 3.34191507e-01 6.39141486e+00
 4.57723561e-02 3.53080849e+01 1.38360657e+02 9.94027376e-01
 3.18826664e+00 4.89846876e-01 1.05142670e+01 5.87790935e+00]


In [48]:
print(whitewine.mean(axis=1)) #행 계산

[21.8855     14.57275    13.62709167 ... 14.08446167 13.47672417
 12.4816175 ]


In [50]:
whitewine[:,0].mean()

6.854787668436097

In [51]:
whitewine[:,0]

array([7. , 6.3, 8.1, ..., 6.5, 5.5, 6. ])

In [53]:
print(whitewine.max(axis=0))

[1.42000e+01 1.10000e+00 1.66000e+00 6.58000e+01 3.46000e-01 2.89000e+02
 4.40000e+02 1.03898e+00 3.82000e+00 1.08000e+00 1.42000e+01 9.00000e+00]


In [55]:
print(whitewine.min(axis=0))

[3.8000e+00 8.0000e-02 0.0000e+00 6.0000e-01 9.0000e-03 2.0000e+00
 9.0000e+00 9.8711e-01 2.7200e+00 2.2000e-01 8.0000e+00 3.0000e+00]


In [66]:
import numpy as np
a=np.arange(15).reshape(-1,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [60]:
a.ndim

2

In [64]:
a.shape

(5, 3)

In [62]:
a.dtype

dtype('int32')

In [78]:
b=np.arange(24); b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [88]:
c=b.reshape(3,2,-1)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [82]:
a=np.arange(24)
a.reshape(2,3,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [86]:
c.itemsize

4

In [87]:
c.ndim

3

In [89]:
b.size

24

In [90]:
c.size

24

In [93]:
d=np.array((2,3,4))

In [94]:
d.dtype

dtype('int32')

In [105]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [108]:
np.ones_like((2,3,4),dtype=np.int16)

array([1, 1, 1], dtype=int16)

In [109]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [110]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [119]:
x=np.linspace(0,2*np.pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [121]:
f=np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [123]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [124]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [125]:
a=np.array([20,30,40,50])
a<35

array([ True,  True, False, False])

In [126]:
A = np.array( [[1,1],
                [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
A@B

array([[5, 4],
       [3, 4]])

In [144]:
rg=np.random.default_rng(1) #함수만드는것!함수가 나옴.
a=np.ones((2,3),dtype=int)
b=rg.random((2,3))
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [142]:
b

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

In [145]:
#np.random.seed(0)
#random 고정시키기. seed번호 뭐든상관 없음. seed 있으면 랜덤하게 또 돌려도 같은 결과값 나옴
np.random.seed(1)
c=np.random.rand(2,3)#0부터 1까지 난수 발생시킴
c

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

In [146]:
>>> rg = np.random.default_rng(1)     # create instance of default random number generator
>>> a = np.ones((2,3), dtype=int)
>>> b = rg.random((2,3))
>>> a *= 3
>>> a

array([[3, 3, 3],
       [3, 3, 3]])

In [147]:
b+=a

In [148]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [149]:
a+=b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [151]:
b.max()

3.950463696325935

In [152]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [157]:
b.sum(axis=1)

array([ 6, 22, 38])

In [155]:
b.min(axis=1)

array([0, 4, 8])

In [156]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [158]:
a=np.arange(6).reshape(2,3)+10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [159]:
np.argmax(a)

5

In [161]:
np.argmax(a,axis=0)

array([1, 1, 1], dtype=int64)

In [165]:
a1=[5,454,87]
a2=[10,54,66]
np.argmax(a1)

1

In [166]:
np.argmax(a1,axis=0)

1

In [168]:
np.argmax(a2,axis=0)

2

In [169]:
a[::-2]

array([[13, 14, 15]])

In [170]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [172]:
a[:6:2]=1000 #0~6번째 사이 2개씩 띄워서 1000으로 바꿔넣기
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [174]:
def f(x,y):
    return 10*x+y

b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [175]:
b[2,3]

23

In [176]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [178]:
b[2:4,1:3]

array([[21, 22],
       [31, 32]])

In [179]:
b[-1]

array([40, 41, 42, 43])

In [183]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [184]:
a=np.floor(10*rg.random((3,4)))

In [185]:
a

array([[8., 4., 5., 0.],
       [7., 5., 3., 7.],
       [3., 4., 1., 4.]])

In [187]:
a.shape

(3, 4)

In [188]:
a.ravel()  # returns the array, flattened

array([8., 4., 5., 0., 7., 5., 3., 7., 3., 4., 1., 4.])

In [189]:
a.reshape(6,2)

array([[8., 4.],
       [5., 0.],
       [7., 5.],
       [3., 7.],
       [3., 4.],
       [1., 4.]])

In [190]:
a.T

array([[8., 7., 3.],
       [4., 5., 4.],
       [5., 3., 1.],
       [0., 7., 4.]])

In [191]:
a.T.shape

(4, 3)

In [194]:
a.resize((2,6))
a

array([[8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4.]])

In [204]:
a = np.floor(10*rg.random((2,2)))
b = np.floor(10*rg.random((2,2)))
a

array([[5., 2.],
       [1., 9.]])

In [205]:
b

array([[5., 1.],
       [6., 7.]])

In [206]:
np.vstack((a,b))

array([[5., 2.],
       [1., 9.],
       [5., 1.],
       [6., 7.]])

In [207]:
np.hstack((a,b))

array([[5., 2., 5., 1.],
       [1., 9., 6., 7.]])

In [208]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [210]:
 a = np.floor(10*rg.random((2,12)))
np.hsplit(a,3)

[array([[6., 9., 0., 5.],
        [5., 7., 1., 8.]]),
 array([[4., 0., 6., 8.],
        [6., 7., 1., 8.]]),
 array([[5., 2., 8., 5.],
        [1., 0., 8., 8.]])]

In [213]:
import pandas as pd
titanic=pd.read_csv("C:/Users/ASIA_08/titanic.csv")

In [214]:
#1 titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [222]:
#2 columns
titanic.shape[1]

12

In [254]:
#1 
titanic.shape

(891, 12)

In [272]:
pd.isna(titanic)
for i in titanic:
if (i="True"):
    print()
    else:
        print("",i)

IndentationError: expected an indented block (<ipython-input-272-3d8c005564bf>, line 3)

In [229]:
#4pclass구분
titanic_class=titanic.groupby(titanic["Pclass"])
titanic_class.mean()

PassengerId  Survived        Age     SibSp     Parch       Fare
Pclass                                                                 
1        461.597222  0.629630  38.233441  0.416667  0.356481  84.154687
2        445.956522  0.472826  29.877630  0.402174  0.380435  20.662183
3        439.154786  0.242363  25.140620  0.615071  0.393075  13.675550

In [259]:
titanic_age=titanic.groupby(titanic["Sex","Age"])
titanic_age=titanic.groupby(titanic["Sex"])
titanic_age.mean()
#5.남자 평균 나이
#5.여자 전체 평균 나이


PassengerId  Survived    Pclass        Age     SibSp     Parch  \
Sex                                                                      
female   431.028662  0.742038  2.159236  27.915709  0.694268  0.649682   
male     454.147314  0.188908  2.389948  30.726645  0.429809  0.235702   

             Fare  
Sex                
female  44.479818  
male    25.523893

In [271]:
#5.남자 평균 나이
#5.여자 전체 평균 나이
titanic_age=titanic[["Sex",'Age']]
titanic_average=titanic_age.groupby(["Sex"])
titanic_average.mean()

Age
Sex              
female  27.915709
male    30.726645

In [257]:
titanic_fare=titanic.groupby(titanic["Fare"])

In [252]:
#6.fare요금 최댓값
titanic['Fare'].max()

512.3292

In [253]:
#요금 최솟값
titanic['Fare'].min()

0.0

In [273]:
titanic.fillna(value=1)

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   1.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500     1        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250     1        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500     1        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000     1        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500     1        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500     1        Q  

[891 rows x 12 columns]